import os
import tarfile
import argparse
from datetime import datetime

# === Argument parsing ===
parser = argparse.ArgumentParser(description="Package session output files into a tar.gz archive")
parser.add_argument("--output-dir", type=str, required=True, help="Directory containing output files")
parser.add_argument("--archive-name", type=str, default="session_outputs.tar.gz", help="Name of the output tar.gz file")
args = parser.parse_args()

output_dir = args.output_dir
archive_path = os.path.join(output_dir, args.archive_name)
readme_path = os.path.join(output_dir, "README_SESSION.txt")

# === Collect files to include ===
included_exts = [".json", ".gif", ".png", ".html", ".sh"]
output_files = [
    os.path.join(output_dir, f)
    for f in os.listdir(output_dir)
    if os.path.splitext(f)[-1] in included_exts and not f.endswith(".tar.gz")
]

# === Generate README file ===
readme_content = f"""
Session Summary – {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

This archive contains outputs from an analysis session using the BFF Grammar package.

Included Files:
- *.json: Usage data for rules across epochs
- *.gif: Animated visualizations of rule frequency or doubling time dynamics
- *.html: Interactive visualizations of rule statistics (e.g. line plots, scatter plots)
- *.sh: Command logs and pipeline runners

Notable Outputs:
- rule_usage_over_time.json: Raw frequency counts of grammar rule usage
- rule_usage_over_time_unique.json: Rule usage where each rule is only counted once per program
- usage_animation.gif: Animation of rule frequency over epochs
- usage_doubling_time.gif: Animation of estimated doubling time of rules over epochs
- rule_frequencies_unique_log.html: Interactive log-scale line plot of top rule frequencies

This README was autogenerated to help you interpret this archive.
"""

with open(readme_path, "w") as f:
    f.write(readme_content)

output_files.append(readme_path)

# === Create tar.gz archive ===
with tarfile.open(archive_path, "w:gz") as tar:
    for file_path in output_files:
        arcname = os.path.basename(file_path)
        tar.add(file_path, arcname=arcname)

print(f"✅ Archive created: {archive_path}")
